module.exports = {
  'layout-body-background': '#f0f2f5',
  'body-background': '#fff',
  'component-background': '#fff',
  'heading-color': '#333',
  'text-color-primary': '#333',
  'text-color': '#666',
  'text-color-secondary': '#999',
  'text-color-inverse': '#fff',
  'shadow-color': 'rgba(0, 0, 0, 0.15)',
  'border-color-split': '#f0f0f0',
  'border-color-line': '#dee2e7',
  'background-color-light': '#fafafa',
  'background-color-base': '#f5f5f5',
  'background-color-multi-tab': '#f4f6f9',
  'background-hover-color': '#fff',
  'table-selected-row-bg': '#fafafa',
  'table-expanded-row-bg': '#fbfbfb',
  'checkbox-check-color': '#fff',
  'disabled-color': 'rgba(0, 0, 0, 0.25)',
  'menu-header-text-color': 'rgba(254, 254, 254, 0.95)',
  'menu-dark-color': 'rgba(254, 254, 254, 0.65)',
  'menu-dark-highlight-color': '#fefefe',
  'menu-dark-arrow-color': '#fefefe',
  'btn-primary-color': '#fff'
};
